### PR TITLE
Mime types

### PR DESCRIPTION
**Pull request by belkka**
I offer to edit file "/usr/share/libfm/archivers.list" during installation.
Lines for addition:

[patool]
create=patool create %F
extract=patool extract %F
extract_to=patool extract %F --outdir %d
mime_types=application/x-rar;application/x-tar;application/zip;application/deb; (list must be longer)

### CODE REVIEW

**Comment by yarikoptic** [comment]
Fwiw editing files belonging to other packages, especially under /use is big no no

**Comment by belkka** [comment]
Well, how about publishing the list of mime types that patool support? Maybe some users would like to edit this file by themself, like me. I use pcmanfm (file manager) and it requires editing "/usr/share/libfm/archivers.list" to use patool as integrated archiver.

**Comment by yarikoptic** [comment]
On Sun, 28 Feb 2016, belkka wrote:

>    Well, how about publishing the list of mime types that patool support?
>    Maybe some users would like to edit this file by themself, like me. I use
>    pcmanfm (file manager) and it requires editing
>    "/usr/share/libfm/archivers.list" to use patool as integrated archiver.

so submit your recommended addition to libfm to include patool in their
listing

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by belkka** [comment]
I have not full list of mime types that patool support. Can you create and publish it? I copied list of mime types for ark. I am not sure that it is right.

Examples from "/usr/share/libfm/archivers.list":
[file-roller]
mime_types=application/x-7z-compressed;application/x-7z-compressed-tar;application/x-ace;application/x-alz;application/x-ar;application/x-arj;application/x-bzip;application/x-bzip-compressed-tar;application/x-bzip1;application/x-bzip1-compressed-tar;application/x-cabinet;application/x-cbr;application/x-cbz;application/x-cd-image;application/x-compress;application/x-compressed-tar;application/x-cpio;application/x-deb;application/x-ear;application/x-ms-dos-executable;application/x-gtar;application/x-gzip;application/x-gzpostscript;application/x-java-archive;application/x-lha;application/x-lhz;application/x-lzip;application/x-lzip-compressed-tar;application/x-lzma;application/x-lzma-compressed-tar;application/x-lzop;application/x-lzop-compressed-tar;application/x-rar;application/x-rar-compressed;application/x-rpm;application/x-rzip;application/x-tar;application/x-tarz;application/x-stuffit;application/x-war;application/x-xz;application/x-xz-compressed-tar;application/x-zip;application/x-zip-compressed;application/x-zoo;application/zip;multipart/x-zip;

[ark]
mime_types=application/x-tar;application/x-compressed-tar;application/x-bzip-compressed-tar;application/x-tarz;application/x-xz-compressed-tar;application/x-lzma-compressed-tar;application/x-deb;application/x-cd-image;application/x-bcpio;application/x-cpio;application/x-cpio-compressed;application/x-sv4cpio;application/x-sv4crc;application/x-rpm;application/x-source-rpm;application/vnd.ms-cab-compressed;application/x-servicepack;application/x-rar;application/x-7z-compressed;application/x-java-archive;application/zip;application/x-compress;application/x-gzip;application/x-bzip;application/x-bzip2;application/x-lzma;application/x-xz;application/lha;application/x-lha;application/maclha;

**Comment by yarikoptic** [comment]
anyways, this PR has nothing what should be merged - contains debian packaging which is to continue its life in Debian packaging repository (at least for now)

**Pull request closed without merging**
